# Server settings
server:
    port: 8086
    # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
    max-http-header-size: 8192
    use-forward-headers: true
    compression:
        enabled: true
        min-response-size: 1024
        mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
    tomcat:
        remote-ip-header: X-Forwarded-for
        protocol-header: X-Forwarded-Proto
        port-header: X-Forwarded-Port
        uri-encoding: UTF-8
# SPRING PROFILES
spring:
    mvc:
        static-path-pattern: /**
    profiles:
        active: 'dev'
    application:
        name: secretBlogBoot-admin
    freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        suffix: .html
        template-loader-path: classpath:/templates/
        settings:
            template_update_delay: 0
            default_encoding: UTF-8
            classic_compatible: true
    # HTTP ENCODING
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    http:
        encoding:
            enabled: true
            charset: UTF-8
            force: true
    messages:
        encoding: UTF-8
    jmx:
        enabled: true
        default-domain: agentservice
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
    banner:
        charset: UTF-8
# MyBatis
#mybatis:
#    type-aliases-package: cn.chenc.blog.business.entity
#    mapper-locations: classpath:/mapper/*.xml
# MyBatis-plus
mybatis-plus:
    # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
    type-aliases-package: cn.chenc.blog.business.entity
    # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
    type-aliases-super-type: java.lang.Object
    mapper-locations: classpath:/mapper/*.xml
    configuration:
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        # 驼峰下划线转换
        map-underscore-to-camel-case: true
        # 配置的缓存的全局开关
        cache-enabled: true
        # 延时加载的开关
        lazy-loading-enabled: true
        # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
        multiple-result-sets-enabled: true
        use-generated-keys: true
        default-statement-timeout: 60
        default-fetch-size: 100
# mapper
mapper:
    mappers: cn.chenc.blog.business.mapper
    not-empty: false
    identity: MYSQL
# pagehelper
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
